server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    hosts:
     - argocd.devopsua.tk
  config:
    url: https://argocd.devopsua.tk
configs:
  secret:
    argocdServerAdminPassword: "$2a$10$QnjaeGBeitbR6jtDFeK7KemojXkdWk/5GSkJrhDqnGlb5MP/Yxseq"  # admin - hash